Bugfix/#16232 cgroup update
redBorder/redborder-cgroups pull request #2
Opened 2024-02-05 15:02 UTC by ljblancoredborder

2024-02-26 10:19 UTC, malvads commented
Also, this doesnt pass the rubocop linter

```
test.rb:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
require 'socket'
^
test.rb:4:1: C: [Correctable] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
    module Checker
^^^^
test.rb:4:5: C: Style/Documentation: Missing top-level documentation comment for module RedBorder::Checker.
    module Checker
    ^^^^^^^^^^^^^^
test.rb:5:5: C: [Correctable] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
        def self.check_memservices_cgroups
    ^^^^
test.rb:5:9: C: Metrics/MethodLength: Method has too many lines. [11/10]
        def self.check_memservices_cgroups ...
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test.rb:7:9: C: [Correctable] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
            Chef::Log::info("Memservices Check")
        ^^^^
test.rb:7:22: C: [Correctable] Style/ColonMethodCall: Do not use :: for method calls.
            Chef::Log::info("Memservices Check")
                     ^^
test.rb:7:29: C: [Correctable] Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
            Chef::Log::info("Memservices Check")
                            ^^^^^^^^^^^^^^^^^^^
test.rb:14:28: C: [Correctable] Layout/SpaceAroundOperators: Surrounding space missing for operator =.
            memory_services=`knife node show #{hostname} -l -F json | jq '.default.redborder.memory_services | keys[]'`.chomp.lines
                           ^
test.rb:14:121: C: Layout/LineLength: Line is too long. [131/120]
            memory_services=`knife node show #{hostname} -l -F json | jq '.default.redborder.memory_services | keys[]'`.chomp.lines
                                                                                                                        ^^^^^^^^^^^
test.rb:15:28: C: [Correctable] Layout/SpaceAroundOperators: Surrounding space missing for operator =.
            active_services=memory_services.select do |s|
                           ^
test.rb:16:13: C: [Correctable] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.
                `systemctl is-active #{s}`.chomp == 'active'
            ^^^^
test.rb:19:82: C: [Correctable] Layout/SpaceAfterComma: Space missing after comma.
              cgroup = `systemctl show -p ControlGroup #{s}`.gsub('ControlGroup=','').chomp
                                                                                 ^
test.rb:20:28: C: [Correctable] Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
              s = s.delete("\",-").chomp
                           ^^^^^^
test.rb:21:55: C: [Correctable] Layout/LeadingCommentSpace: Missing space after #.
              cgroup.include?("redborder-#{s}.slice") #assigned cgroup should cointain redborder-webui.slice ie, else false
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test.rb:21:121: C: Layout/LineLength: Line is too long. [123/120]
              cgroup.include?("redborder-#{s}.slice") #assigned cgroup should cointain redborder-webui.slice ie, else false
                                                                                                                        ^^^
test.rb:27:45: C: [Correctable] Style/MethodCallWithoutArgsParentheses: Do not use parentheses for method calls with no arguments.
RedBorder::Checker.check_memservices_cgroups()
                                            ^^

1 file inspected, 17 offenses detected, 13 offenses autocorrectable
```

2024-02-26 10:23 UTC, malvads requested changes, later dismissed
This PR needs to be linted before merge

2024-02-26 10:23 UTC, malvads commented on resources/scripts/rb_check_cgroups.rb
> +            # Chef::Config[:http_retry_count] = 5
why there is unused code here?

2024-02-26 10:23 UTC, malvads commented on resources/scripts/rb_check_cgroups.rb
> +            # memory_services=node.default.memory_services.keys()
also here

2024-02-26 10:23 UTC, malvads commented on packaging/rpm/redborder-cgroups.spec
> +- Ruby wrapper added
the version is missing here

2024-02-26 10:23 UTC, malvads commented on resources/scripts/rb_check_cgroups.rb
> +RedBorder::Checker.check_memservices_cgroups()
Using parentheses with no arguments?

2024-03-07 11:21 UTC, ViMesTor approved these changes

2024-03-07 11:27 UTC, merged